all: main.css default.css magres.css

main.css: main.scss ; sass main.scss > main.css

magres.css: magres.scss ; sass magres.scss > magres.css

default.css: default.scss ; sass default.scss > default.css

