name: Tim Green
markdown: redcarpet
pygments: true
include: ['_pages', '_posts']
relative_permalinks: false
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

